### PR TITLE
Enable type checking in Continuous Integration

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This Pull Request adds type checking to a continuous integration (CI) process outside of the two CI systems currently encoded in this repository.  The CI workflow set up uses GitHub Actions, but in a matter naïve to other systems that have some scripting written in this repository.  E.g., I'm not familiar with `tox`.

Feedback or revisions are welcome on this PR.  My objective with the PR is to type-check code on the way in.  I'm aware that there are other tests, but I'm not sure how they're all meant to be called, so the PR starts small: Check types on the oldest and newest Python releases designated in `pyproject.toml`.

## Disclaimer:

Participation by NIST in the creation of the documentation of mentioned software is not intended to imply a recommendation or endorsement by the National Institute of Standards and Technology, nor is it intended to imply that any specific software is necessarily the best available for the purpose.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Ah, and apparently, some setting may need to be turned on in order to run GitHub Actions on this repository (possibly Settings / Actions / General / Allow [x] actions and reusable workflows).  IIRC, closing the PR and re-opening it will trigger an Action run.

**Comment by ashleysommer** [comment]
@ajnelson-nist 
> may need to be turned on in order to run GitHub Actions on this repository (possibly Settings / Actions / General / Allow [x] actions and reusable workflows

The option "Allow _all_ actions and reusable workflows" is already enabled.

**Comment by ajnelson-nist** [comment]
Is there a checkbox, or "Run first Action" interface, at the bottom of this PR in the view of any project Administrators?

If not:  I have a hunch that the CI not firing is an anti-abuse mechanism.  I'm not a project maintainer, so I probably can't initiate the Actions infrastructure.  I think if a project maintainer adds an Actions YAML workflow file first, CI would start firing on this.

I'd thought project Contributors could get by this, but it seems no, & in the bigger picture that's fine by me.

Maybe just the first 36 lines of the YAML in this PR should be merged first?  I'll file another PR.

**Comment by ashleysommer** [comment]
After merging #252, the tests on here are now running!

**Comment by ashleysommer** [comment]
Passed type checking!

**Pull request merged**
