### PR TITLE
Remove dependency on rdflib-jsonld

### LINKED ISSUE #93: Remove (soft)dependency on rdflib_jsonld
https://github.com/RDFLib/pySHACL/issues/92 fixed RDFLib 6.0, but a big change in RDFlib 6.0 was integrating `rdflib_jsonld` into RDFlib itself: https://github.com/RDFLib/rdflib/pull/1354

Due to this, the rdflib_jsonld project has been archived and is not maintained anymore: https://github.com/RDFLib/rdflib-jsonld#archived

Since rdflib_jsonld cannot be installed anymore with the newest version of setuptools, since it has use_2to3 set to true, see https://github.com/pypa/setuptools/issues/2769, this makes pySHACL unusable with JSON-LD with the newest version of setuptools.

`Graph().serialize(format='json-ld')` should just work out of the box now with RDFLib 6.0.

One slightly related issue (but irrelevant if the move away from rdflib_jsonld is done) is that the code in https://github.com/RDFLib/pySHACL/blob/master/pyshacl/rdfutil/load.py#L21-L26 doesn't work: 
```
File "/home/zenon/DEV/ETH/renku-python/renku/core/utils/shacl.py", line 21, in <module>
    from pyshacl import validate
  File "/home/zenon/.pyenv/versions/renku-python/lib/python3.7/site-packages/pyshacl/__init__.py", line 4, in <module>
    from .shapes_graph import ShapesGraph
  File "/home/zenon/.pyenv/versions/renku-python/lib/python3.7/site-packages/pyshacl/shapes_graph.py", line 7, in <module>
    from .constraints.constraint_component import CustomConstraintComponentFactory
  File "/home/zenon/.pyenv/versions/renku-python/lib/python3.7/site-packages/pyshacl/constraints/__init__.py", line 4, in <module>
    from pyshacl.constraints.constraint_component import ConstraintComponent
  File "/home/zenon/.pyenv/versions/renku-python/lib/python3.7/site-packages/pyshacl/constraints/constraint_component.py", line 36, in <module>
    from pyshacl.rdfutil import stringify_node
  File "/home/zenon/.pyenv/versions/renku-python/lib/python3.7/site-packages/pyshacl/rdfutil/__init__.py", line 7, in <module>
    from .load import get_rdf_from_web, load_from_source  # noqa: F401
  File "/home/zenon/.pyenv/versions/renku-python/lib/python3.7/site-packages/pyshacl/rdfutil/load.py", line 22, in <module>
    import rdflib_jsonld  # noqa: F401
ModuleNotFoundError: No module named 'rdflib_jsonld'
```
It raises a ModuleNotFoundError for me, not an IndexError on Python 3.7.4

### PR DESCRIPTION
**Pull request by Panaetius**
Closes #93 

Requires https://github.com/RDFLib/OWL-RL/pull/46 to be merged and released first, then needs a `poetry lock`.

Isort reordered some imports in ` pyshacl/validate.py`, I can undo that but as it is right now it should follow the CONTRIBUTING guidelines of the project.

### CODE REVIEW

**Comment by ashleysommer** [comment]
I don't know why Black changed so many lines in various unrelated files in the commit.
I ran [re-black and isort on the whole codebase two months ago](https://github.com/RDFLib/pySHACL/commit/1b29e5fa807b88c3b50590ad60c438dba7bdc61e) when I updated the required version of Black to 21.6b0, so they should all already be in the correct state.

Did you run with the given Black config file? `black --config=./pyproject.toml ./pyshacl`?

Regarding isort, that has a mind of its own. It seems to reorder imports on random files all the time, and a couple of commits later it will re-order them back..

**Comment by Panaetius** [comment]
I did 
```
$ pip install black==21.6b0
$ black --verbose --config ./pyproject.toml pyshacl
```
in the virtual env for the project (same with `poetry run black ...`).

I believe this is correct behavior, see https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas . Black will split a collection of arguments to separate lines if they and in a trailing comma. I remember there used to be a bug in black where, if you call it, it'd add a trailing comma to these kinds of argument lists, which would then cause it to break them onto separate lines if run again (so running black twice didn't yield the same result as running it once). This has since been fixed, but maybe you ran into that issue?

On a side note, we've had good experiences using `pre-commit` with this config file: https://github.com/SwissDataScienceCenter/renku-python/blob/master/.pre-commit-config.yaml and mentioning in our CONTRIBUTING.md that a user should do `pre-commit install`. Then black will complain if a user tries to commit a file that wasn't properly formatted. Just a small quality of life improvement you might be interested in.

**Comment by ashleysommer** [comment]
> psf/black#1629 this was the black issue, that was in 20.8b0

Yep, looks like you're right. this is that bug. I had pinned our version of black to 20.6b0 back in June because that was the first version which contained the `required-version` param, so we could enforce a specific version of black being used.

I'll update it to v20.8b0 to fix that bug.

**Comment by ashleysommer** [comment]
@Panaetius 
PySHACL v0.16.2 is released, with the ImportError bug fixed, and the required version of Black bumped to 21.8b0 to fix the black bug. Reblacked all source files, which brought in the same formatting changes as seen in this PR.

This PR should now be able to be rebased against current Master to make the changeset smaller.

**Review by ashleysommer — CHANGES_REQUESTED** [review]
Please rebase or merge against current master

**Comment by Panaetius** [comment]
I've rebased on current master.

**Pull request merged**
