### PR TITLE
Fix typo in cli.py and README

### PR DESCRIPTION
**Pull request by ajnelson-nist**
In case it matters: I applied the README fix by hand, making a guess on the line wrapping.

### CODE REVIEW

**Comment by ashleysommer** [comment]
@ajnelson-nist  Thanks for this. I knew about this type and actually thought I fixed it months ago. Maybe I didn't push the change.
Seems like your small change in cli.py has caused the `black` tool to complain about the file formatting. I'll see if there is an easy fix for that.

**Comment by ajnelson-nist** [comment]
@ashleysommer I applied the `black` reformatting.  It wanted the string to go to one line.  Strangely, this was the original output it suggested:

```diff
diff --git a/pyshacl/cli.py b/pyshacl/cli.py
index fb33ce4..f38c799 100644
--- a/pyshacl/cli.py
+++ b/pyshacl/cli.py
@@ -53,8 +53,7 @@ parser.add_argument(
     dest='metashacl',
     action='store_true',
     default=False,
-    help='Validate the SHACL Shapes graph against the shacl-shacl '
-    'Shapes Graph before validating the Data Graph.',
+    help='Validate the SHACL Shapes graph against the shacl-shacl ' 'Shapes Graph before validating the Data Graph.',
 )
 parser.add_argument(
     '-im',
```

I went a step further and removed the string juxtaposition, but FYI, I see there is at least one other spot `black` had done that before (the `--ont-graph` flag).

**Comment by ashleysommer** [comment]
Thanks heaps!

**Comment by ashleysommer** [comment]
@ajnelson-nist This fix is released in latest PySHACL v0.17.3

**Comment by ajnelson-nist** [comment]
Thank you!

**Pull request merged**
