### PR TITLE
remove value_node_to_string() to fix Issue 133

### LINKED ISSUE #133: sh:pattern isn't interpreted correctly
This this SHACL graph:

```turtle
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@base <http://www.opengis.net/def/geosparql/validator/> .

<S16-wkt-content>
	a sh:NodeShape ;
	sh:property <S16-wkt-content-sub-start> ;
	sh:targetSubjectsOf geo:asWKT ;
.

<S16-wkt-content-sub-start>
	a sh:PropertyShape ;
	sh:path geo:asWKT ;
	sh:pattern "^\\s*$|^\\s*(P|C|S|L|T|<)" ;
	sh:flags "i" ;
	sh:message "The content of an RDF literal with an incoming geo:asWKT relation must conform to a well-formed WKT string, as defined by its official specification (Simple Features Access)."@en ;
.
```

and this data

```turtle
# Valid: testing asWKT predicate & matching datatype

@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

<https://example.com/geometry-a>
    geo:asWKT "POINT (153.084231 -27.322738)"^^geo:wktLiteral ;
.

<https://example.com/geometry-b>
    geo:asWKT "xPOINT (153.084231 -27.322738)"^^geo:wktLiteral ;
.

<https://example.com/geometry-c>
    geo:asWKT "(153.084231 -27.322738)"^^geo:wktLiteral ;
.

<https://example.com/geometry-d>
    geo:asWKT "     POINT (153.084231 -27.322738)"^^geo:wktLiteral ;
.

<https://example.com/geometry-e>
    geo:asWKT "     "^^geo:wktLiteral ;
.

<https://example.com/geometry-f>
    geo:asWKT ""^^geo:wktLiteral ;
.
```

I expect only two invalid results: `<https://example.com/geometry-b>` & `<https://example.com/geometry-c>` according to the `sh:pattern`, however pySHACL returns 5 invalid results: all focus nodes.

[SHACL Playground](https://shacl.org/playground/) returns the expected result.

A pattern of `^None` passes for all focus nodes! So the problem is that the value node is not being read in correctly.

### PR DESCRIPTION
**Pull request by nicholascar**
The function `value_node_to_string()` called `str(v.value)` for a Literal else `str(v)` but this was returning None for Literal which meant pySHACL couldn't validate `sh:pattern` matches.

The fix was also to call `str(v)` for Literal thereby making the function return the same output regardless of input type, just:

```python
def value_node_to_string(v):
    return str(v)
```

So I've removed the function and included a test. After removal, all other tests pass without any further code alterations.

Fixes #133

### CODE REVIEW

**Comment by ashleysommer** [comment]
Hi Nick.
Thanks for the PR. I'll have to look into this one a little bit before merging it. 
There must be something else odd going on here.
All `sh:pattern` tests in the SHACL W3C test suite, and the DASH Shapes test suite pass without issue.
And calling `str(v.value)` on a `Literal` should get the string, not `None`, unless maybe the turtle parser is getting tricked up on the regex pattern and creating a bad Literal?
I'll dig a bit further and let you know. (I'm aware this fix is time-senstive).

**Comment by nicholascar** [comment]
I suspect this is due to changes in RDFLib that mean you don't need to do `v.value` any more for a literal. So they probably all did pass on older versions of RDFLib but perhaps fail on 6.1.1??? Just a guess...

**Comment by ashleysommer** [comment]
> So they probably all did pass on older versions of RDFLib but perhaps fail on 6.1.1??? 

No, that's not it. The whole SHACL test suite passes on RDFLib v6.1.1 without modification. I'm looking further into it now to see if I can get to the bottom of where this issue is coming from.

**Comment by ashleysommer** [comment]
Ok, I misread the report initially. I thought you said was getting `None` from the `sh:pattern` literal (the Regex pattern). But its getting `None` on the WKT strings (the Value node, as you mentioned in your original report).

Because `asWKT` string is not a `xsd:string` or `xsd:langString` (or any other XSD type known in RDFLib) RDFLib does not covert it to a python value, so it is not accessible via the Literal's `.value` property.

I've made a small tweak to the `value_node_to_string` method to account for this, it fixes the problem, and it will be available in the next PySHACL release (later today).

**Comment by nicholascar** [comment]
> Because asWKT string is not a xsd:string or xsd:langString...

Of course! I had an inkling initially that it was because `sh:pattern` was only looking for "strings" not custom data types, but then I forgot about that... and the "fix" I implemented seemed to work (solved my problem and passed all tests). But yeah, better is to actually handle the root cause you've made explicit here.

**Comment by ashleysommer** [comment]
All good. PySHACL v0.19.0 is release now, with this fix in it. We can close this PR.

**Comment by nicholascar** [comment]
Thanks @ashleysommer, great to be able to put pySHACL in the GeoSPARQL test suite this weekend!

**Pull request closed without merging**
