### PR TITLE
Fix typo in ontology used for test

### PR DESCRIPTION
**Pull request by atomobianco**
Spot a typo for a data property which was supposed to be camel case

### CODE REVIEW

**Comment by ashleysommer** [comment]
Thanks @atomobianco

**Comment by ashleysommer** [comment]
Can you please make the same fix in "test_inoculate.py",  "test_manual_targeting.py", "issues/test_014.py", and "cmdline_tests/o1.ttl"
The same snippet of test ontology code is used in all of those.

**Comment by atomobianco** [comment]
And an additional one, done in https://github.com/RDFLib/pySHACL/pull/275/commits/10c958eaac8cc04ea7f3ec524bd2a9b266d2bf74

**Comment by atomobianco** [comment]
If you thumb-up this comment I'll do a single commit ;)

**Pull request merged**
