### PR TITLE
build: upgrade pyduktape2

### PR DESCRIPTION
**Pull request by aucampia**
This change updates the version of pyduktape2 in pyproject.toml to a version that sets a restriction on the version of CPython. This is needed because pyduktape2 does not build with the latest version of CPython.

- Fixes <https://github.com/RDFLib/pySHACL/issues/202>.

### CODE REVIEW

**Comment by aucampia** [comment]
Seems mypy is failing now on python 3.8, 3.10 and 3.11, I will try make a PR to fix that a bit later

**Comment by ajnelson-nist** [comment]
> Seems mypy is failing now on python 3.8, 3.10 and 3.11, I will try make a PR to fix that a bit later

@aucampia : I noticed the `mypy` failures too when I was checking up on `pyshacl.validate`'s signature.  I filed [PR 192](https://github.com/RDFLib/pySHACL/pull/192) as an intermediary fix.  There will be more to do after that PR if it's merged.

**Comment by ashleysommer** [comment]
This PR includes only the updated poetry.lock file. Is it supposed to have the updated pyproject.toml file too?

**Comment by aucampia** [comment]
> This PR includes only the updated poetry.lock file. Is it supposed to have the updated pyproject.toml file too?

The version range in pyproject.toml already includes the newly released version:

https://github.com/RDFLib/pySHACL/blob/eda96e12b6a20659e71dd1d24298a1ffed1c27a9/pyproject.toml#L63

But when poetry installs dependencies it uses the specific versions in poetry.lock:

https://github.com/RDFLib/pySHACL/blob/eda96e12b6a20659e71dd1d24298a1ffed1c27a9/poetry.lock#L617-L625

So this only updates the locked version. In RDFLib this is updated by Dependabot.

**Comment by ashleysommer** [comment]
Yeah, thanks, I thought maybe that is what you were going for.
BTW, I opened a discussion thread about the merits of including a lockfile in PySHACL, and the differing use cases of PySHACL as and Application vs PySHACL as a library.
https://github.com/RDFLib/pySHACL/issues/204

**Pull request merged**
