### PR TITLE
DOC: README.md: markdown formatting, syntax

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by westurner** [comment]
Also note that (this may be a separate issue) installing pyshacl does not install enough dependencies to run `-h/--help`:

```bash
$ pip install pyshacl
$ pyshacl -h
...
ModuleNotFoundError: No module named 'requests'
```

So the installation instructions should probably also mention that any of these are sufficient:

```bash
pip install pyshacl requests
pip install pyshacl aiohttp
pip install pyshacl requests aiohttp
```

**Comment by ashleysommer** [comment]
`requests` should not be required to run `pyshacl -h`. I'll look into that.

**Comment by ashleysommer** [comment]
Ok, looks like that is a bug introduced in PySHACL 0.13.0 from September. Actually it is an RDFLib 5.0.0 bug, but it was exposed by the addition of SPARQLFunction support to PySHACL in 0.13.0.

I will ensure that PySHACL doesn't import anything SPARQL-related until it really needs to (and especially not for the CLI tool).

**Comment by ashleysommer** [comment]
Hi, yes that fix is released now as part of v0.14.2

**Pull request merged**
